project_name: node-detacher
builds:
  - id: node-detacher
    main: ./
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/mumoshu/node-detacher/Version={{.Version}}
changelog:
  filters:
    # commit messages matching the regexp listed here will be removed from
    # the changelog
    # Default is empty
    exclude:
      - '^docs:'
      - typo
dockers:
  - goos: linux
    goarch: amd64
    goarm: ''
    binaries:
      - node-detacher
    builds:
      - node-detacher
    image_templates:
      - "mumoshu/node-detacher:latest"
      - "mumoshu/node-detacher:{{ .Tag }}"
      - "mumoshu/node-detacher:v{{ .Major }}"
    build_flag_templates:
      - "--pull"
    dockerfile: Dockerfile.release
