# permissions to do edit runners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: runner-editor-role
rules:
- apiGroups:
  - node-detacher.variant.run
  resources:
  - attachments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - node-detacher.variant.run
  resources:
  - attachments/status
  verbs:
  - get
  - patch
  - update
