# permissions to do viewer runners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: runner-viewer-role
rules:
- apiGroups:
  - node-detacher.variant.run
  resources:
  - attachments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - node-detacher.variant.run
  resources:
  - attachments/status
  verbs:
  - get
