name: Continuous Integration
on:
 pull_request:
   types: [opened, synchronize, reopened]
 push:
   branches:
     - master

jobs:
  report:
    name: Report
    runs-on: ubuntu-latest
    steps:
    - name: ref
      run: echo ${{ github.ref }}
    - name: event_name
      run: echo ${{ github.event_name }}
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Install kubebuilder
      run: |
        curl -L -O https://github.com/kubernetes-sigs/kubebuilder/releases/download/v2.2.0/kubebuilder_2.2.0_linux_amd64.tar.gz
        tar zxvf kubebuilder_2.2.0_linux_amd64.tar.gz
        sudo mv kubebuilder_2.2.0_linux_amd64 /usr/local/kubebuilder
    - uses: actions/setup-go@v1
      with:
        go-version: '1.13.8'
    - name: ci
      run: make ci BUILD=local
    - name: hub login
      if: (github.event_name == 'push' && endsWith(github.ref,'/master')) || (github.event_name == 'create' && startsWith(github.ref,'refs/tags/'))
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: deploy   # when merged into master, tag master and push - ideally, this would be a separate job, but you cannot share docker build cache between jobs
      if: github.event_name == 'push' && endsWith(github.ref,'/master')
      run: |
        TAG=latest make push
